accounts/urls.py
from django.urls import path, include

from .views import RegistrationView, ProfileView, EditProfileView

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', RegistrationView.as_view(), name='register'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('profile/edit', EditProfileView.as_view(), name='profile-edit'),
]

boards/urls.py
from django.urls import path, include
from .forms import *
from .views import BoardCreateView, BoardCreationForm, BoardDetailView, BoardAddCommentView

app_name = 'boards'
urlpatterns = [
    path('', BoardCreateView.as_view(), name='index'),
    path('<str:pk>', BoardDetailView.as_view(), name='detail'),
    path('<str:pk>/comment', BoardAddCommentView.as_view(), name='add-comment'),
]

core/urls.py
from django.urls import path, include

app_name = 'core'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('profilepic', UploadFileForm.as_view(), name='profilepic')
]

edgde/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('videos/', include('videos.urls', namespace='videos')),
    path('boards/', include('boards.urls', namespace='boards')),
    path('transactions/', include('transactions.urls', namespace='transactions')),
    path('progressbarupload/', include('progressbarupload.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link href='/static/css/site.css' rel="stylesheet">
    <link rel="stylesheet" href="https://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    {% block stylesheets %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
     <a class="navbar-brand" href="#">{{ title }}</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarCollapse">
       <ul class="navbar-nav mr-auto">
         <li class="nav-item active">
           <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#">GRABS</a>
         </li>
         <li class="nav-item">
           <a class="nav-link disabled" href="#">Disabled</a>
         </li>
       </ul>
       <form class="form-inline mt-2 mt-md-0">
         <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
         <button href="" class="btn btn-outline-success my-2 my-sm-0" type="submit" placeholder="Find GRABS and Channels here...">Search</button>
       </form>
     </div>
   </nav>

    <header>
      {% if user.is_authenticated %}

      <a href="{% url 'accounts:logout' %}" type="button" class="btn btn-outline-danger">Logout</a>
      {% else %}
      <a href="{% url 'accounts:login' %}" type="button" class="btn btn-outline-danger">Login</a>
      <a href="{% url 'accounts:register' %}" type="button" class="btn btn-outline-danger">Sign Up</a>
      {% endif %}

    </header>
    <div id="content">
      {% block content %}{% endblock %}

    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% block scripts %}{% endblock %}
    <div class="footer"><h5><p>Copyright &copy; 2017 Edgde Inc </p></h5></div>
    <!-- view our <a href="#">Terms of service</a> and <a href="#">Privacy Policy</a>here -->

  </body>
</html>

templates/layout2.html
{% load cloudinary %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/static/imgs/first-favicon.gif">


    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/colortemplates/BLK_393431.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">EDGDE &#8482;</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"></a>

        </ul>
        <form class="form-inline mt-2 mt-md-0">
          {% if user.is_authenticated %}

          <a href="{% url 'accounts:logout' %}" type="button" class="btn btn-secondary">Logout</a>
          {% else %}
          <a href="{% url 'accounts:login' %}" type="button" class="btn btn-secondary">Login</a>
          <a href="{% url 'accounts:register' %}" type="button" class="btn btn-secondary">Sign Up</a>
          {% endif %}
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'accounts:profile' %}">Homepage<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Channels</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'boards:index' %}">Boards</a>
            </li>
          </ul>

          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="#">Account Settings</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Homepage Settings</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Alerts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Uploads</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Medals</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
          </ul>

          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="#">  Profile for {{ user.username }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Points: {{ user.points }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:profile-edit' %}">PICTURE: <br><img width="150px" src="/media/{{ request.user.image }}">
              <h6>(edit)</h6></a>

            </li>
          </ul>


        </nav>
        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
          <div id="content">
            {% block content %}{% endblock %}
          </div>

          <!-- last viewable item is here -->
          <div class="footer"><h5><p>Copyright &copy; 2017 Edgde Inc &#8482;</p></h5></div>
        </main>
      </div>
    </div>





    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src='/static/js/site.js'></script>
    {% block secret %}{% endblock %}
    {% cloudinary_includes %}
    {% cloudinary_js_config %}

    </script>
    <!-- <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->
    </script>
  </body>
</html>